#!/bin/bash

# recordRTSP  :   bash script to record rtsp video stream from IP camera
# record segments of 3MP RTSP H.264 stream into stdout in .mp4 format files
# using openRTSP from  http://www.live555.com/openRTSP/#source-code

# Note: if recording process is terminated unexpectedly, "moov atom" containing
# index info will be missing from end of file, and .mp4 file will not be playable

# start at boot time: add to /etc/rc.local  
# (sudo -u user /usr/local/bin/recordRTSP) &

# restart every midnight from "user" crontab:
# 0 0 * * * /usr/local/bin/recordRTSP


VIDEO_DIR="/media/sdb1/CAM0"
STREAM="rtsp://192.168.1.50/0"
PIDLOC="/home/user/recordRTSPpid"
P2="/home/user/openRTSPpid"
SEG=300     # how many seconds long each mp4 file is

# 1 day = 1440 minutes = 86400 seconds
# 1 day = 288 intervals of 5 minutes

RPID=$(<"$PIDLOC")    # PID of previous recordRTSP process

if [[ $( ps -o pid= -p $RPID  ) ]]; then
     kill -s SIGHUP $RPID    # stop process if running. (SIGHUP preserves .mp4 integrity)
fi

echo $$ > $PIDLOC    # store process ID for future control of process

for i in `seq 1 289`;
do
  TD=$(date +"%Y%m%d-%H%M%S")  # current time and date as YYYYMMDD-HHMMSS
  OPID=$(<"$P2")    # get PID of previous openRTSP process
  if [[ $( ps -o pid= -p $OPID  ) ]]; then   # if it's still extant, get rid of it
    kill -s SIGHUP $OPID
  fi
  openRTSP -B 1200000 -b 1200000 -4 -w 2048 -h 1536 -f 15 -d $SEG $STREAM > $VIDEO_DIR/$TD.mp4 &
  echo $! > $P2
  echo "Waiting for process $! to exit"
  wait $!
done
